on:
  push:
    branches:
      - master
name: Master Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Update permissions on mvnw
        run: chmod 700 mvnw
      - name: Build, Test
        run: ./mvnw clean verify --no-transfer-progress