on: push
name: Push
jobs:
  mavenBuild:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Maven Build
      uses: LucaFeger/action-maven-cli@1.1.0
      with:
        args: clean package
