on: push
name: Push
jobs:
  mavenBuild:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Maven Build
      uses: LucaFeger/action-maven-cli@765e218a50f02a12a7596dc9e7321fc385888a27
      with:
        args: clean package
